export const SET_CUR_NAV_INDEX = 'SET_CUR_NAV_INDEX'

export const SET_PHONE = 'SET_PHONE'

export const SET_START_PLACE = 'SET_START_PLACE'

export const SET_FORMATTED_START_PLACE = 'SET_FORMATTED_START_PLACE'

export const SET_DESTINATION = 'SET_DESTINATION'

export const SET_START_POSITION = 'SET_START_POSITION'

export const SET_END_POSITION = 'SET_END_POSITION'

export const SET_CUR_CITY = 'SET_CUR_CITY'

export const SET_DRIVER = 'SET_DRIVER'

export const SET_COST = 'SET_COST'



